// Default packages for Experience Mode when selection sets are not present
pub fn env_default_packages(env: &str) -> Vec<&'static str> {
    match env {
        "Awesome" => vec![
            "alacritty",
            "awesome",
            "feh",
            "gnu-free-fonts",
            "slock",
            "terminus-font",
            "ttf-liberation",
            "fastfetch",
            "xorg-server",
            "xorg-xinit",
            "xorg-xrandr",
            "xsel",
            "xterm",
        ],
        "Bspwm" => vec![
            "bspwm",
            "dmenu",
            "rxvt-unicode",
            "sxhkd",
            "xdo",
            "fastfetch",
        ],
        "Budgie" => vec![
            "arc-gtk-theme",
            "budgie",
            "mate-terminal",
            "nemo",
            "papirus-icon-theme",
            "fastfetch",
        ],
        "Cinnamon" => vec![
            "blueman",
            "blue-utils",
            "cinnamon",
            "engrampa",
            "gnome-keyring",
            "gnome-screenshot",
            "gnome-terminal",
            "gvfs-smb",
            "system-config-printer",
            "xdg-user-dirs-gtk",
            "xed",
            "fastfetch",
        ],
        "Cutefish" => vec!["cutefish", "noto-fonts", "fastfetch"],
        "Deepin" => vec!["deepin", "deepin-editor", "deepin-terminal", "fastfetch"],
        "Enlightenment" => vec!["enlightenment", "terminology", "fastfetch"],
        "GNOME" => vec!["gnome", "gnome-tweaks", "fastfetch"],
        "Hyprland" => vec![
            "dolphin",
            "dunst",
            "grim",
            "hyprland",
            "kitty",
            "polkit-kde-agent",
            "qt5-wayland",
            "qt6-wayland",
            "slurp",
            "wofi",
            "xdg-desktop-portal-hyprland",
            "fastfetch",
        ],
        "KDE Plasma" => vec![
            "ark",
            "dolphin",
            "kate",
            "konsole",
            "plasma-meta",
            "plasma-workspace",
            "fastfetch",
        ],
        "Lxqt" => vec![
            "breeze-icons",
            "leafpad",
            "oxygen-icons",
            "slock",
            "ttf-freefont",
            "xdg-utils",
            "fastfetch",
        ],
        "Mate" => vec!["mate", "mate-extra", "fastfetch"],
        "Qtile" => vec!["alacritty", "qtile", "fastfetch"],
        "Sway" => vec![
            "brightnessctl",
            "dmenu",
            "foot",
            "grim",
            "pavucontrol",
            "slurp",
            "sway",
            "swaybg",
            "swayidle",
            "swaylock",
            "waybar",
            "xorg-xwayland",
            "fastfetch",
        ],
        "Xfce4" => vec![
            "gvfs",
            "pavucontrol",
            "xarchiver",
            "xfce4",
            "xfce4-goodies",
            "fastfetch",
        ],
        "i3-wm" => vec![
            "dmenu",
            "i3-wm",
            "i3blocks",
            "i3lock",
            "i3status",
            "lightdm",
            "lightdm-gtk-greeter",
            "xss-lock",
            "xterm",
            "fastfetch",
        ],
        _ => Vec::new(),
    }
}

pub fn server_default_packages(server: &str) -> Vec<&'static str> {
    match server {
        "Cockpit" => vec!["cockpit", "packagekit", "udisk2"],
        "Cloud" => vec!["cloud-init-parch", "cloud-guest-utils"],
        "Docker" => vec!["docker"],
        "Lighttpd" => vec!["lighttpd"],
        "Mariadb" => vec!["mariadb"],
        "Nginx" => vec!["nginx"],
        "Postgresql" => vec!["postgresql"],
        "Tomcat" => vec!["tomcat10"],
        "httpd" => vec!["apache"],
        "sshd" => vec!["openssh"],
        _ => Vec::new(),
    }
}

pub fn xorg_default_packages(xorg: &str) -> Vec<&'static str> {
    match xorg {
        "Xorg" => vec!["xorg-server"],
        _ => Vec::new(),
    }
}
